"""autogenerated by genpy from baxter_msgs/GripperProperties.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class GripperProperties(genpy.Message):
  _md5sum = "d3b24964f2ce5ed7da642fe492f91d45"
  _type = "baxter_msgs/GripperProperties"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# Gripper properties
#
bool   hasForce             # true if the gripper has force control
bool   hasPosition          # true if the gripper has position control
bool   isReverse	    # true if the gripper grips when opened


"""
  __slots__ = ['hasForce','hasPosition','isReverse']
  _slot_types = ['bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       hasForce,hasPosition,isReverse

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GripperProperties, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.hasForce is None:
        self.hasForce = False
      if self.hasPosition is None:
        self.hasPosition = False
      if self.isReverse is None:
        self.isReverse = False
    else:
      self.hasForce = False
      self.hasPosition = False
      self.isReverse = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3B.pack(_x.hasForce, _x.hasPosition, _x.isReverse))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 3
      (_x.hasForce, _x.hasPosition, _x.isReverse,) = _struct_3B.unpack(str[start:end])
      self.hasForce = bool(self.hasForce)
      self.hasPosition = bool(self.hasPosition)
      self.isReverse = bool(self.isReverse)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3B.pack(_x.hasForce, _x.hasPosition, _x.isReverse))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 3
      (_x.hasForce, _x.hasPosition, _x.isReverse,) = _struct_3B.unpack(str[start:end])
      self.hasForce = bool(self.hasForce)
      self.hasPosition = bool(self.hasPosition)
      self.isReverse = bool(self.isReverse)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3B = struct.Struct("<3B")
