"""autogenerated by genpy from baxter_msgs/GripperIdentity.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class GripperIdentity(genpy.Message):
  _md5sum = "5c423d2a28bbc9289e3befaa316bbb56"
  _type = "baxter_msgs/GripperIdentity"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """string name       # Gripper type name
uint8  type       # Gripper type identifier
# Heartland gripper type enumeration:
    uint8  NO_GRIPPER = 0
    uint8  SUCTION_CUP_GRIPPER = 1
    uint8  PNEUMATIC_GRIPPER = 2
    uint8  ELECTRIC_GRIPPER = 128
#
uint8  hardware_id   # Gripper hardware id
# Gripper hardware id enumeration:
    uint8  INVALID_GRIPPER_HARDWARE_ID = 0
uint8  version_major # Gripper version, 0 if none
uint8  version_minor # Gripper version, 0 if none
uint8  revision_lsb  # Gripper revision number, 0 if none

"""
  # Pseudo-constants
  NO_GRIPPER = 0
  SUCTION_CUP_GRIPPER = 1
  PNEUMATIC_GRIPPER = 2
  ELECTRIC_GRIPPER = 128
  INVALID_GRIPPER_HARDWARE_ID = 0

  __slots__ = ['name','type','hardware_id','version_major','version_minor','revision_lsb']
  _slot_types = ['string','uint8','uint8','uint8','uint8','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       name,type,hardware_id,version_major,version_minor,revision_lsb

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GripperIdentity, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.name is None:
        self.name = ''
      if self.type is None:
        self.type = 0
      if self.hardware_id is None:
        self.hardware_id = 0
      if self.version_major is None:
        self.version_major = 0
      if self.version_minor is None:
        self.version_minor = 0
      if self.revision_lsb is None:
        self.revision_lsb = 0
    else:
      self.name = ''
      self.type = 0
      self.hardware_id = 0
      self.version_major = 0
      self.version_minor = 0
      self.revision_lsb = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_5B.pack(_x.type, _x.hardware_id, _x.version_major, _x.version_minor, _x.revision_lsb))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.name = str[start:end].decode('utf-8')
      else:
        self.name = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.type, _x.hardware_id, _x.version_major, _x.version_minor, _x.revision_lsb,) = _struct_5B.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_5B.pack(_x.type, _x.hardware_id, _x.version_major, _x.version_minor, _x.revision_lsb))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.name = str[start:end].decode('utf-8')
      else:
        self.name = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.type, _x.hardware_id, _x.version_major, _x.version_minor, _x.revision_lsb,) = _struct_5B.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_5B = struct.Struct("<5B")
