/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/p/peth8881/robotics/ws_baxter/src/baxter_common/baxter_msgs/msg/GripperState.msg
 *
 */


#ifndef BAXTER_MSGS_MESSAGE_GRIPPERSTATE_H
#define BAXTER_MSGS_MESSAGE_GRIPPERSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace baxter_msgs
{
template <class ContainerAllocator>
struct GripperState_
{
  typedef GripperState_<ContainerAllocator> Type;

  GripperState_()
    : enabled(0)
    , calibrated(0)
    , ready(0)
    , moving(0)
    , gripping(0)
    , missed(0)
    , error(0)
    , command(0)
    , position(0.0)
    , force(0.0)  {
    }
  GripperState_(const ContainerAllocator& _alloc)
    : enabled(0)
    , calibrated(0)
    , ready(0)
    , moving(0)
    , gripping(0)
    , missed(0)
    , error(0)
    , command(0)
    , position(0.0)
    , force(0.0)  {
    }



   typedef uint8_t _enabled_type;
  _enabled_type enabled;

   typedef uint8_t _calibrated_type;
  _calibrated_type calibrated;

   typedef uint8_t _ready_type;
  _ready_type ready;

   typedef uint8_t _moving_type;
  _moving_type moving;

   typedef uint8_t _gripping_type;
  _gripping_type gripping;

   typedef uint8_t _missed_type;
  _missed_type missed;

   typedef uint8_t _error_type;
  _error_type error;

   typedef uint8_t _command_type;
  _command_type command;

   typedef float _position_type;
  _position_type position;

   typedef float _force_type;
  _force_type force;


    enum { STATE_FALSE = 0 };
     enum { STATE_TRUE = 1 };
     enum { STATE_UNKNOWN = 2 };
     enum { CMD_IDLE = 0 };
     enum { CMD_GET_ID = 1 };
     enum { CMD_RESET_ALL = 2 };
     enum { CMD_RESET_FSM = 3 };
     enum { CMD_CALIBRATE = 4 };
     enum { CMD_PREPARE_TO_GRIP = 5 };
     enum { CMD_GRIP = 6 };
     enum { CMD_RELEASE = 7 };
     enum { CMD_GOTO = 8 };
     enum { CMD_STOP = 9 };
     enum { CMD_SET = 10 };
     enum { CMD_CLEAR_CALIBRATION = 11 };
     static const float POSITION_CLOSED;
     static const float POSITION_OPEN;
     static const float FORCE_MIN;
     static const float FORCE_MAX;
 

  typedef boost::shared_ptr< ::baxter_msgs::GripperState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::baxter_msgs::GripperState_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct GripperState_

typedef ::baxter_msgs::GripperState_<std::allocator<void> > GripperState;

typedef boost::shared_ptr< ::baxter_msgs::GripperState > GripperStatePtr;
typedef boost::shared_ptr< ::baxter_msgs::GripperState const> GripperStateConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   
   template<typename ContainerAllocator> const float
      GripperState_<ContainerAllocator>::POSITION_CLOSED =
        
          0.0
        
        ;
   

   
   template<typename ContainerAllocator> const float
      GripperState_<ContainerAllocator>::POSITION_OPEN =
        
          100.0
        
        ;
   

   
   template<typename ContainerAllocator> const float
      GripperState_<ContainerAllocator>::FORCE_MIN =
        
          0.0
        
        ;
   

   
   template<typename ContainerAllocator> const float
      GripperState_<ContainerAllocator>::FORCE_MAX =
        
          100.0
        
        ;
   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::baxter_msgs::GripperState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::baxter_msgs::GripperState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace baxter_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'baxter_msgs': ['/home/p/peth8881/robotics/ws_baxter/src/baxter_common/baxter_msgs/msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/hydro/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::baxter_msgs::GripperState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::baxter_msgs::GripperState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::baxter_msgs::GripperState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::baxter_msgs::GripperState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::baxter_msgs::GripperState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::baxter_msgs::GripperState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::baxter_msgs::GripperState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0eac783439e05e6ea33b1ff617fab794";
  }

  static const char* value(const ::baxter_msgs::GripperState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0eac783439e05e6eULL;
  static const uint64_t static_value2 = 0xa33b1ff617fab794ULL;
};

template<class ContainerAllocator>
struct DataType< ::baxter_msgs::GripperState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "baxter_msgs/GripperState";
  }

  static const char* value(const ::baxter_msgs::GripperState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::baxter_msgs::GripperState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# The following Gripper State fields are tristate: 0 = false; 1 = true; 2 = unknown/unsupported\n\
  uint8   STATE_FALSE = 0\n\
  uint8   STATE_TRUE = 1\n\
  uint8   STATE_UNKNOWN = 2\n\
#\n\
uint8   enabled             # true if enabled\n\
uint8   calibrated          # true if calibration has completed\n\
uint8   ready               # true if ready to grip\n\
uint8   moving              # true if moving\n\
uint8   gripping            # true if gripping\n\
uint8   missed              # true if GRIP/GOTO/SET was commanded and the gripper reaches the end of travel\n\
uint8   error               # true if the gripper is in an error state\n\
#\n\
uint8   command             # current gripper command, one of the following:\n\
  # Note that while these have the same as values as the gripper opcodes they\n\
  # are not used that way.\n\
  uint8   CMD_IDLE            = 0 \n\
  uint8   CMD_GET_ID          = 1\n\
  uint8   CMD_RESET_ALL       = 2\n\
  uint8   CMD_RESET_FSM       = 3\n\
  uint8   CMD_CALIBRATE       = 4\n\
  uint8   CMD_PREPARE_TO_GRIP = 5\n\
  uint8   CMD_GRIP            = 6\n\
  uint8   CMD_RELEASE         = 7\n\
  uint8   CMD_GOTO            = 8\n\
  uint8   CMD_STOP            = 9\n\
  uint8   CMD_SET             = 10\n\
  uint8   CMD_CLEAR_CALIBRATION = 11\n\
#\n\
float32 position            # position as a percentage of the max position;      0=closed - 100=open\n\
#\n\
  float32 POSITION_CLOSED = 0.0\n\
  float32 POSITION_OPEN   = 100.0\n\
#\n\
float32 force               # force as a percentage of max force;                0=none   - 100=max\n\
#\n\
  float32 FORCE_MIN = 0.0\n\
  float32 FORCE_MAX = 100.0\n\
#\n\
\n\
";
  }

  static const char* value(const ::baxter_msgs::GripperState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::baxter_msgs::GripperState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.enabled);
      stream.next(m.calibrated);
      stream.next(m.ready);
      stream.next(m.moving);
      stream.next(m.gripping);
      stream.next(m.missed);
      stream.next(m.error);
      stream.next(m.command);
      stream.next(m.position);
      stream.next(m.force);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct GripperState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::baxter_msgs::GripperState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::baxter_msgs::GripperState_<ContainerAllocator>& v)
  {
    s << indent << "enabled: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enabled);
    s << indent << "calibrated: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.calibrated);
    s << indent << "ready: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ready);
    s << indent << "moving: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.moving);
    s << indent << "gripping: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.gripping);
    s << indent << "missed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.missed);
    s << indent << "error: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.error);
    s << indent << "command: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.command);
    s << indent << "position: ";
    Printer<float>::stream(s, indent + "  ", v.position);
    s << indent << "force: ";
    Printer<float>::stream(s, indent + "  ", v.force);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BAXTER_MSGS_MESSAGE_GRIPPERSTATE_H
