controller_list:
  - name: fake_left_arm_controller
    joints:
      - left_s0
      - left_s1
      - left_e0
      - left_e1
      - left_w0
      - left_w1
      - left_w2
  - name: fake_left_hand_controller
    joints:
      - left_gripper_l_finger_joint