joint_limits:
  left_gripper_l_finger_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  left_w1:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  left_w0:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  left_e0:
    has_velocity_limits: true
    max_velocity: 2.5
    has_acceleration_limits: false
    max_acceleration: 0
  left_s1:
    has_velocity_limits: true
    max_velocity: 2.5
    has_acceleration_limits: false
    max_acceleration: 0
  left_w2:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  left_e1:
    has_velocity_limits: true
    max_velocity: 2.5
    has_acceleration_limits: false
    max_acceleration: 0
  left_gripper_r_finger_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  left_s0:
    has_velocity_limits: true
    max_velocity: 2.5
    has_acceleration_limits: false
    max_acceleration: 0